/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:551a58f3-f402-4c8d-8197-b43e26e7f5a0",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_72fZiSlSf",
    "aws_user_pools_web_client_id": "4t2bgk2rkdd320rcdjfasf1rkd",
    "oauth": {}
};


export default awsmobile;
